version: "3.7"

services:
  tcs-front:
    image: lcbutch/tcs-front:master
    depends_on:
      - "tcs-service"
      - "letsencrypt"
    expose:
      - "5000"
    env_file:
      - .env
    restart: always

  tcs-service:
    image: lcbutch/tcs-service:master
    depends_on:
      - "tcs-db"
      - "letsencrypt"
    expose:
      - "80"
    env_file:
      - .env
    restart: always

  tcs-db:
    image: postgres
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  letsencrypt:
    image: linuxserver/letsencrypt
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/config/nginx/site-confs

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  db-data:
