version: "3.7"

services:
  tcs-front:
    image: lcbutch/tcs-front:master
    depends_on:
      - "tcs-service"
    expose:
      - "5000"
    env_file:
      - .env
    restart: always

  tcs-service:
    image: lcbutch/tcs-service:master
    depends_on:
      - "tcs-db"
    expose:
      - "80"
    env_file:
      - .env
    restart: always

  tcs-db:
    image: microsoft/mssql-server-linux
    env_file:
      - .env
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql
    restart: always

  letsencrypt:
    image: linuxserver/letsencrypt
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/config/nginx/site-confs
    depends_on:
      - "tcs-front"
      - "tcs-service"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  db-data:
