version: "3.7"

services:
  tcs-front:
    image: lcbutch/tcs-front:prod
    depends_on:
      - "tcs-service"
    ports:
      - "80:80"

  tcs-service:
    image: lcbutch/tcs-service:master
    depends_on:
      - "tcs-db"
    ports:
      - "8080:80"
    env_file:
      - .env

  tcs-db:
    image: microsoft/mssql-server-linux
    env_file:
      - .env
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  db-data:
