version: "3.7"

services:
  tcs-integration:
    build:
      context: ./backend/
      dockerfile: Test.Dockerfile
    depends_on:
      - tcs-db
    environment:
      Db:ConnectionString: "Host=tcs-db;Database=test;Username=test;Password=Develop@90"
  tcs-db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: TCS
      POSTGRES_PASSWORD: Develop@90
