version: "3.0"

services:
  tcs-front:
    build:
      context: ./frontend/
    depends_on:
      - "tcs-service"
    expose:
      - "5000"
    env_file:
      - .env
    restart: always

  tcs-service:
    image: lcbutch/tcs-service:master
    depends_on:
      - "tcs-db"
    expose:
      - "80"
    env_file:
      - .env
    restart: always

  tcs-db:
    image: microsoft/mssql-server-linux
    env_file:
      - .env
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql
    restart: always

  letsencrypt:
    image: linuxserver/letsencrypt
    environment:
      URL: "levibutcher.com"
      VALIDATION: "http"
      TZ: ""
      STAGING: "True"
      ONLY_SUBDOMAINS: "TRUE"
      SUBDOMAINS: "devtcs"
      EMAIL: "levibutcher355@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/config/nginx/site-confs
    depends_on:
      - "tcs-front"
      - "tcs-service"

volumes:
  db-data:
