version: "3.7"

services:
  tcs-integration:
    build:
      context: ./backend/
      dockerfile: Test.Dockerfile
    depends_on:
      - tcs-db
    environment:
      Db:ConnectionString: "Server=tcs-db;Database=TCS;User Id=SA;Password=Develop@90"
  tcs-db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Develop@90
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
