version: "3.7"

services:
  tcs-front:
    build:
      context: ./frontend/
    depends_on:
      - "tcs-service"
    ports:
      - "5000"
    restart: always

  tcs-service:
    build:
      context: ./backend/tcs-service
    depends_on:
      - "tcs-db"
    env_file:
      - .env
    restart: always

  tcs-db:
    image: microsoft/mssql-server-linux
    env_file:
      - .env
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql
    restart: always

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  letsencrypt:
    image: linuxserver/letsencrypt
    environment:
      URL: "sxbdev.com"
      VALIDATION: "http"
      TZ: ""
      STAGING: "True"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/le-ssl/:/etc/letsencrypt

volumes:
  db-data:
