// flow-typed signature: 6eafe6aa8df22eb4167831a3c2fe628b
// flow-typed version: <<STUB>>/react-loading-overlay_v^1.0.1/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loading-overlay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loading-overlay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loading-overlay/__tests__/LoadingOverlay.test' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/es6/components/Spinner' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/es6/LoadingOverlay' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/es6/styles' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/lib/components/Spinner' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/lib/LoadingOverlay' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/lib/styles' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/umd/LoadingOverlay' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/umd/LoadingOverlay.min' {
  declare module.exports: any;
}

declare module 'react-loading-overlay/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loading-overlay/__tests__/LoadingOverlay.test.js' {
  declare module.exports: $Exports<'react-loading-overlay/__tests__/LoadingOverlay.test'>;
}
declare module 'react-loading-overlay/es6/components/Spinner.js' {
  declare module.exports: $Exports<'react-loading-overlay/es6/components/Spinner'>;
}
declare module 'react-loading-overlay/es6/LoadingOverlay.js' {
  declare module.exports: $Exports<'react-loading-overlay/es6/LoadingOverlay'>;
}
declare module 'react-loading-overlay/es6/styles.js' {
  declare module.exports: $Exports<'react-loading-overlay/es6/styles'>;
}
declare module 'react-loading-overlay/lib/components/Spinner.js' {
  declare module.exports: $Exports<'react-loading-overlay/lib/components/Spinner'>;
}
declare module 'react-loading-overlay/lib/LoadingOverlay.js' {
  declare module.exports: $Exports<'react-loading-overlay/lib/LoadingOverlay'>;
}
declare module 'react-loading-overlay/lib/styles.js' {
  declare module.exports: $Exports<'react-loading-overlay/lib/styles'>;
}
declare module 'react-loading-overlay/umd/LoadingOverlay.js' {
  declare module.exports: $Exports<'react-loading-overlay/umd/LoadingOverlay'>;
}
declare module 'react-loading-overlay/umd/LoadingOverlay.min.js' {
  declare module.exports: $Exports<'react-loading-overlay/umd/LoadingOverlay.min'>;
}
declare module 'react-loading-overlay/webpack.config.js' {
  declare module.exports: $Exports<'react-loading-overlay/webpack.config'>;
}
