// flow-typed signature: 71e3169f0ef3815f9cc733e4d02e6f76
// flow-typed version: <<STUB>>/react-spinners_v^0.5.13/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/helpers' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/helpers/proptypes' {
  declare module.exports: any;
}

declare module 'react-spinners/dist' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/interfaces' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/main-18515d17b41d66af802f' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/main-2b455c5c3c2731fe04e7' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/main-5188210867ae25fff0fe' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/main-adaf5d63b974b2d89676' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/main-b3dd9e3b9f544a669a3c' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/main-f385b0433be3ef6f361d' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/vendors~main-18515d17b41d66af802f' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/vendors~main-2b455c5c3c2731fe04e7' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/vendors~main-5188210867ae25fff0fe' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/vendors~main-adaf5d63b974b2d89676' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/vendors~main-b3dd9e3b9f544a669a3c' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/js/vendors~main-f385b0433be3ef6f361d' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/main-fab79780f85857889681' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/scripts' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/vendors~main-fab79780f85857889681' {
  declare module.exports: any;
}

declare module 'react-spinners/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/code' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/color_picker' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/form' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/loader_item' {
  declare module.exports: any;
}

declare module 'react-spinners/examples' {
  declare module.exports: any;
}

declare module 'react-spinners/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/proptypes' {
  declare module.exports: any;
}

declare module 'react-spinners/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/prettier.config' {
  declare module.exports: any;
}

declare module 'react-spinners/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/helpers' {
  declare module.exports: any;
}

declare module 'react-spinners/src/helpers/proptypes' {
  declare module.exports: any;
}

declare module 'react-spinners/src' {
  declare module.exports: any;
}

declare module 'react-spinners/src/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-spinners/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinners/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/BarLoader'>;
}
declare module 'react-spinners/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/BeatLoader'>;
}
declare module 'react-spinners/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/BounceLoader'>;
}
declare module 'react-spinners/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/CircleLoader'>;
}
declare module 'react-spinners/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClimbingBoxLoader'>;
}
declare module 'react-spinners/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClipLoader'>;
}
declare module 'react-spinners/dist/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/BarLoader'>;
}
declare module 'react-spinners/dist/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/BeatLoader'>;
}
declare module 'react-spinners/dist/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/BounceLoader'>;
}
declare module 'react-spinners/dist/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/CircleLoader'>;
}
declare module 'react-spinners/dist/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/ClimbingBoxLoader'>;
}
declare module 'react-spinners/dist/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/ClipLoader'>;
}
declare module 'react-spinners/dist/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/DotLoader'>;
}
declare module 'react-spinners/dist/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/FadeLoader'>;
}
declare module 'react-spinners/dist/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/GridLoader'>;
}
declare module 'react-spinners/dist/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/HashLoader'>;
}
declare module 'react-spinners/dist/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/dist/helpers/colors'>;
}
declare module 'react-spinners/dist/helpers/index' {
  declare module.exports: $Exports<'react-spinners/dist/helpers'>;
}
declare module 'react-spinners/dist/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/dist/helpers'>;
}
declare module 'react-spinners/dist/helpers/proptypes.js' {
  declare module.exports: $Exports<'react-spinners/dist/helpers/proptypes'>;
}
declare module 'react-spinners/dist/index' {
  declare module.exports: $Exports<'react-spinners/dist'>;
}
declare module 'react-spinners/dist/index.js' {
  declare module.exports: $Exports<'react-spinners/dist'>;
}
declare module 'react-spinners/dist/interfaces.js' {
  declare module.exports: $Exports<'react-spinners/dist/interfaces'>;
}
declare module 'react-spinners/dist/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/MoonLoader'>;
}
declare module 'react-spinners/dist/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/PacmanLoader'>;
}
declare module 'react-spinners/dist/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/PropagateLoader'>;
}
declare module 'react-spinners/dist/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/PulseLoader'>;
}
declare module 'react-spinners/dist/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/RingLoader'>;
}
declare module 'react-spinners/dist/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/RiseLoader'>;
}
declare module 'react-spinners/dist/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/RotateLoader'>;
}
declare module 'react-spinners/dist/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/ScaleLoader'>;
}
declare module 'react-spinners/dist/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/SkewLoader'>;
}
declare module 'react-spinners/dist/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/SquareLoader'>;
}
declare module 'react-spinners/dist/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/SyncLoader'>;
}
declare module 'react-spinners/docs/js/main-18515d17b41d66af802f.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/main-18515d17b41d66af802f'>;
}
declare module 'react-spinners/docs/js/main-2b455c5c3c2731fe04e7.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/main-2b455c5c3c2731fe04e7'>;
}
declare module 'react-spinners/docs/js/main-5188210867ae25fff0fe.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/main-5188210867ae25fff0fe'>;
}
declare module 'react-spinners/docs/js/main-adaf5d63b974b2d89676.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/main-adaf5d63b974b2d89676'>;
}
declare module 'react-spinners/docs/js/main-b3dd9e3b9f544a669a3c.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/main-b3dd9e3b9f544a669a3c'>;
}
declare module 'react-spinners/docs/js/main-f385b0433be3ef6f361d.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/main-f385b0433be3ef6f361d'>;
}
declare module 'react-spinners/docs/js/vendors~main-18515d17b41d66af802f.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/vendors~main-18515d17b41d66af802f'>;
}
declare module 'react-spinners/docs/js/vendors~main-2b455c5c3c2731fe04e7.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/vendors~main-2b455c5c3c2731fe04e7'>;
}
declare module 'react-spinners/docs/js/vendors~main-5188210867ae25fff0fe.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/vendors~main-5188210867ae25fff0fe'>;
}
declare module 'react-spinners/docs/js/vendors~main-adaf5d63b974b2d89676.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/vendors~main-adaf5d63b974b2d89676'>;
}
declare module 'react-spinners/docs/js/vendors~main-b3dd9e3b9f544a669a3c.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/vendors~main-b3dd9e3b9f544a669a3c'>;
}
declare module 'react-spinners/docs/js/vendors~main-f385b0433be3ef6f361d.js' {
  declare module.exports: $Exports<'react-spinners/docs/js/vendors~main-f385b0433be3ef6f361d'>;
}
declare module 'react-spinners/docs/main-fab79780f85857889681.js' {
  declare module.exports: $Exports<'react-spinners/docs/main-fab79780f85857889681'>;
}
declare module 'react-spinners/docs/scripts.js' {
  declare module.exports: $Exports<'react-spinners/docs/scripts'>;
}
declare module 'react-spinners/docs/vendors~main-fab79780f85857889681.js' {
  declare module.exports: $Exports<'react-spinners/docs/vendors~main-fab79780f85857889681'>;
}
declare module 'react-spinners/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/DotLoader'>;
}
declare module 'react-spinners/examples/components/code.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/code'>;
}
declare module 'react-spinners/examples/components/color_picker.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/color_picker'>;
}
declare module 'react-spinners/examples/components/form.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/form'>;
}
declare module 'react-spinners/examples/components/index' {
  declare module.exports: $Exports<'react-spinners/examples/components'>;
}
declare module 'react-spinners/examples/components/index.js' {
  declare module.exports: $Exports<'react-spinners/examples/components'>;
}
declare module 'react-spinners/examples/components/loader_item.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/loader_item'>;
}
declare module 'react-spinners/examples/index' {
  declare module.exports: $Exports<'react-spinners/examples'>;
}
declare module 'react-spinners/examples/index.jsx' {
  declare module.exports: $Exports<'react-spinners/examples'>;
}
declare module 'react-spinners/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/FadeLoader'>;
}
declare module 'react-spinners/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/GridLoader'>;
}
declare module 'react-spinners/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/HashLoader'>;
}
declare module 'react-spinners/helpers/index' {
  declare module.exports: $Exports<'react-spinners/helpers'>;
}
declare module 'react-spinners/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/helpers'>;
}
declare module 'react-spinners/helpers/proptypes.js' {
  declare module.exports: $Exports<'react-spinners/helpers/proptypes'>;
}
declare module 'react-spinners/index' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/index.js' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/MoonLoader'>;
}
declare module 'react-spinners/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/PacmanLoader'>;
}
declare module 'react-spinners/prettier.config.js' {
  declare module.exports: $Exports<'react-spinners/prettier.config'>;
}
declare module 'react-spinners/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/PropagateLoader'>;
}
declare module 'react-spinners/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/PulseLoader'>;
}
declare module 'react-spinners/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/RingLoader'>;
}
declare module 'react-spinners/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/RiseLoader'>;
}
declare module 'react-spinners/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/RotateLoader'>;
}
declare module 'react-spinners/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/ScaleLoader'>;
}
declare module 'react-spinners/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/SkewLoader'>;
}
declare module 'react-spinners/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/SquareLoader'>;
}
declare module 'react-spinners/src/BarLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/BarLoader'>;
}
declare module 'react-spinners/src/BeatLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/BeatLoader'>;
}
declare module 'react-spinners/src/BounceLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/BounceLoader'>;
}
declare module 'react-spinners/src/CircleLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/CircleLoader'>;
}
declare module 'react-spinners/src/ClimbingBoxLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/ClimbingBoxLoader'>;
}
declare module 'react-spinners/src/ClipLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/ClipLoader'>;
}
declare module 'react-spinners/src/DotLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/DotLoader'>;
}
declare module 'react-spinners/src/FadeLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/FadeLoader'>;
}
declare module 'react-spinners/src/GridLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/GridLoader'>;
}
declare module 'react-spinners/src/HashLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/HashLoader'>;
}
declare module 'react-spinners/src/helpers/index' {
  declare module.exports: $Exports<'react-spinners/src/helpers'>;
}
declare module 'react-spinners/src/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/src/helpers'>;
}
declare module 'react-spinners/src/helpers/proptypes.js' {
  declare module.exports: $Exports<'react-spinners/src/helpers/proptypes'>;
}
declare module 'react-spinners/src/index' {
  declare module.exports: $Exports<'react-spinners/src'>;
}
declare module 'react-spinners/src/index.js' {
  declare module.exports: $Exports<'react-spinners/src'>;
}
declare module 'react-spinners/src/MoonLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/MoonLoader'>;
}
declare module 'react-spinners/src/PacmanLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/PacmanLoader'>;
}
declare module 'react-spinners/src/PropagateLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/PropagateLoader'>;
}
declare module 'react-spinners/src/PulseLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/PulseLoader'>;
}
declare module 'react-spinners/src/RingLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/RingLoader'>;
}
declare module 'react-spinners/src/RiseLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/RiseLoader'>;
}
declare module 'react-spinners/src/RotateLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/RotateLoader'>;
}
declare module 'react-spinners/src/ScaleLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/ScaleLoader'>;
}
declare module 'react-spinners/src/SkewLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/SkewLoader'>;
}
declare module 'react-spinners/src/SquareLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/SquareLoader'>;
}
declare module 'react-spinners/src/SyncLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/SyncLoader'>;
}
declare module 'react-spinners/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/SyncLoader'>;
}
declare module 'react-spinners/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-spinners/webpack.config.dev'>;
}
declare module 'react-spinners/webpack.config.js' {
  declare module.exports: $Exports<'react-spinners/webpack.config'>;
}
